version: '3'

services:
  basket:
    image: basket-service
    container_name: basket-service
    build:
      context: ./basket-service
      dockerfile: DockerFile
    ports:
      - '${BASKET_PORT}:${BASKET_PORT}'
    environment:
      PORT: ${BASKET_PORT}      
      ORDERS_API_URL: http://order:${ORDER_PORT} 
      STOCK_API_URL: http://stock:${STOCK_PORT} 
      DB_URL: mongodb://database:27017
      SERVICE_NAME: 'basket-service'
    command: npm start
    networks:
      - apis   
    depends_on:    
      - database
    volumes:
      - "./basket-service:/basket-service"
      - ./basket-service/node_modules
  order:
    image: order-service
    container_name: order-service
    build:
      context: ./order-service
      dockerfile: DockerFile
    ports:
      - '${ORDER_PORT}:${ORDER_PORT}'
    environment:
      PORT: ${ORDER_PORT}         
      DB_URL: mongodb://database:27017 
      SERVICE_NAME: order-service      
    command: npm start  
    networks:
      - apis 
    depends_on:    
      - database 
    volumes:
      - "./order-service:/order-service"   
      - ./order-service/node_modules               
  payment:
    image: payment-service
    container_name: payment-service
    build:
      context: ./payment-service
      dockerfile: DockerFile
    ports:
      - '${PAYMENT_PORT}:${PAYMENT_PORT}'
    environment:
      PORT: ${PAYMENT_PORT}            
      DB_URL: mongodb://database:27017 
      SERVICE_NAME: payment-service   
    command: npm start
    networks:
      - apis  
    depends_on:    
      - database      
    volumes:
      - "./payment-service:/payment-service"
      - ./payment-service/node_modules 
  product:
    image: product-service
    container_name: product-service
    build:
      context: ./product-service
      dockerfile: DockerFile
    ports:
      - '${PRODUCT_PORT}:${PRODUCT_PORT}'
    environment:
      PORT: ${PRODUCT_PORT}  
      DB_URL: mongodb://database:27017  
      SERVICE_NAME: product-service            
    command: npm start   
    networks:
      - apis   
    depends_on:    
      - database 
    volumes:
      - "./product-service:/product-service"      
      - ./product-service/node_modules         
  # shipping:
  #   image: shipping-service
  #   container_name: shipping-service
  #   build:
  #     context: ./shipping-service
  #     dockerfile: DockerFile
  #   ports:
  #     - '${SHIPPING_PORT}:${SHIPPING_PORT}'
  #   environment:
  #     PORT: ${SHIPPING_PORT} 
  #     DB_URL: mongodb://database:27017            
  #   command: npm start   
  #   networks:
  #     - apis 
  #   volumes:
  #     - "./shipping-service:/shipping-service"  
  #     - ./shipping-service/node_modules   
  stock:
    image: stock-service
    container_name: stock-service
    build:
      context: ./stock-service
      dockerfile: DockerFile
    ports:
      - '${STOCK_PORT}:${STOCK_PORT}'
    environment:
      PORT: ${STOCK_PORT}         
      SERVICE_NAME: stock-service   
    command: npm start        
    networks:
      - apis 
    depends_on:    
      - database  
    volumes:
      - "./stock-service:/stock-service"       
      - ./stock-service/node_modules           
  user:
    image: user-service
    container_name: user-service
    build:
      context: ./user-service
      dockerfile: DockerFile
    ports:
      - '${USER_PORT}:${USER_PORT}'
    environment:
      PORT: ${USER_PORT}
      DB_URL: mongodb://database:27017
      SERVICE_NAME: user-service
    command: npm start
    networks:
      - apis  
    depends_on:    
      - database      
    volumes:
      - "./user-service:/user-service"    
      - ./user-service/node_modules   
  database:
    image: mongo:latest
    container_name: "mongodb"
    volumes:
      - csecommerce:/data/db
    ports:
      - 27017:27017
    networks:
      - apis
  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    ports:
      - "8080:15672"
    networks:
      - apis
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password
    volumes:
      - ./docker:/var/run/docker.sock
  consul:
    image: consul:latest
    container_name: consul
    command: "consul agent -dev -ui -client 0.0.0.0"
    ports:
      - "8500:8500"     
      - "8600:8600/udp"
    networks:
      - apis
  saga:
    image: saga-orchestrator
    container_name: saga-orchestrator
    build:
      context: ./saga-orchestrator
      dockerfile: DockerFile
    ports:
      - '${SAGA_PORT}:${SAGA_PORT}'
    environment:
      PORT: ${SAGA_PORT}
      ORDERS_API_URL: http://order:${ORDER_PORT} 
      DB_URL: mongodb://database:27017
      SERVICE_NAME: saga-orchestrator      
    command: npm start  
    networks:
      - apis 
    depends_on:    
      - database 
    volumes:
      - "./saga-orchestrator:/saga-orchestrator"   
      - ./saga-orchestrator/node_modules               
volumes:
    csecommerce:
networks: 
  apis: